Algoritmo "LaçoDeRepetiçãoFor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaison
// Descrição   : Vendo o for no visual G
// Autor(a)    : Pedro Satana
// Data atual  : 28/03/2025
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contador de 10 ate 1 passo -1 faca
      escreval(contador)
   fimpara

Fimalgoritmo