Algoritmo "repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaison
// Descrição   : Usando o laço de repetição repita
// Autor(a)    : Pedro Santana
// Data atual  : 26/03/2025
Var
   // Seção de Declarações das variáveis
   contador:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   repita
      escreval("Seu dia mais facil foi ontem!")
      contador <- contador + 1
   ate contador > 9 entao


Fimalgoritmo